2020-03-23 14:52:43.425 +01:00 [ERR] Not Found
   at API_CARGA.Models.Services.OaiPublishRDFService.CallGetApi(String urlMethod) in C:\Hercules\AutoGeneradorUris\UrisFactoryGit\GnossDeustoBackend\API_CARGA\API_CARGA\Models\Services\OaiPublishRDFService.cs:line 96
   at API_CARGA.Models.Services.OaiPublishRDFService.CallListIdentifier(Guid identifierRepo) in C:\Hercules\AutoGeneradorUris\UrisFactoryGit\GnossDeustoBackend\API_CARGA\API_CARGA\Models\Services\OaiPublishRDFService.cs:line 33
   at API_CARGA.Models.Services.OaiPublishRDFService.PublishRepositories(Guid identifier) in C:\Hercules\AutoGeneradorUris\UrisFactoryGit\GnossDeustoBackend\API_CARGA\API_CARGA\Models\Services\OaiPublishRDFService.cs:line 23
   at UrisFactory.Controllers.syncController.PostSyncro(Guid identifier) in C:\Hercules\AutoGeneradorUris\UrisFactoryGit\GnossDeustoBackend\API_CARGA\API_CARGA\Controllers\syncController.cs:line 58
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at API_CARGA.Middlewares.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\Hercules\AutoGeneradorUris\UrisFactoryGit\GnossDeustoBackend\API_CARGA\API_CARGA\Middlewares\ErrorHandlingMiddleware.cs:line 24

